include(FetchContent)

SET(SDL_SHARED FALSE)
SET(SDL2_DISABLE_UNINSTALL TRUE)

FETCHCONTENT_DECLARE(
    SDL2Source
    GIT_REPOSITORY https://github.com/libsdl-org/SDL.git
    GIT_TAG release-2.26.1
)
FETCHCONTENT_MAKEAVAILABLE(SDL2Source)
INCLUDE_DIRECTORIES(${SDL2Source_SOURCE_DIR})